[project]
name = "ling-final-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "modal>=0.68.6",
    "pandas>=2.2.3",
]
